#
# autor: Sergey Shimanskiy
#
apiVersion: v1
kind: Service
metadata:
  name: confluence
spec:
  ports:
    - port: 8090
  selector:
    app: confluence
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: confluence
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: confluence
    spec:
      containers:
      - name: confluence
        image: flyer8/atlassian-confluence:latest
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: confluence-volume
          mountPath: /var/atlassian/confluence
      volumes:
        - name: confluence-volume
          hostPath:
         # directory location on host
            path: /opt/atlassian/confluence