#
# autor: Sergey Shimanskiy
#
apiVersion: v1
kind: Service
metadata:
  name: jira
spec:
  ports:
    - port: 8080
  selector:
    app: jira
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jira
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: cptactionhank/atlassian-jira:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jira-volume
          mountPath: /var/atlassian/jira
#        - name: jira-volume-logs
#          mountPath: /var/atlassian/jira/logs
      volumes:
        - name: jira-volume
          hostPath:
         # directory location on host
            path: /opt/atlassian/jira