---
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.122.10
  ports:
  - port: 1
- addresses:
  - ip: 192.168.122.11
  ports:
  - port: 1
---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1